# Change these first
owner: mvanschellebeeck # Your GitHub organization or username, where this repository lives
repo: unbiased-science-uptime # The name of this repository

sites:
  # Re-enable after GA filters requests out
  # - name: Unbiased Science Sources
  #   url: https://uspodsources.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /unbiased-science-uptime
  logoUrl: https://uspodsources.com/favicon.ico
  name: Unbiased Science Uptime
  introTitle: "View the the status of **Unbiased Science Sources**"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
